// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAp8EdIgELbOWpt4vVqHCHzApL1TC0HA4',
    appId: '1:79594856324:web:cee5361c47e7df8ca8c7d1',
    messagingSenderId: '79594856324',
    projectId: 'fruits-hub-6fd25',
    authDomain: 'fruits-hub-6fd25.firebaseapp.com',
    storageBucket: 'fruits-hub-6fd25.appspot.com',
    measurementId: 'G-C2Z1YM0Q37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtsuZilfSJDTK6pg8IoVfw3fGUpCxsR94',
    appId: '1:79594856324:android:6c80f22308e4ad78a8c7d1',
    messagingSenderId: '79594856324',
    projectId: 'fruits-hub-6fd25',
    storageBucket: 'fruits-hub-6fd25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR69oKZgrIDqBiG0NS1lSNwWkVPvJK0x8',
    appId: '1:79594856324:ios:6e86376c2444df48a8c7d1',
    messagingSenderId: '79594856324',
    projectId: 'fruits-hub-6fd25',
    storageBucket: 'fruits-hub-6fd25.appspot.com',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR69oKZgrIDqBiG0NS1lSNwWkVPvJK0x8',
    appId: '1:79594856324:ios:6e86376c2444df48a8c7d1',
    messagingSenderId: '79594856324',
    projectId: 'fruits-hub-6fd25',
    storageBucket: 'fruits-hub-6fd25.appspot.com',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAp8EdIgELbOWpt4vVqHCHzApL1TC0HA4',
    appId: '1:79594856324:web:e97b5410a630d03ba8c7d1',
    messagingSenderId: '79594856324',
    projectId: 'fruits-hub-6fd25',
    authDomain: 'fruits-hub-6fd25.firebaseapp.com',
    storageBucket: 'fruits-hub-6fd25.appspot.com',
    measurementId: 'G-SJNCGV1XZN',
  );
}
